// flow-typed signature: fbd33eedc3ac68d6dd96d193616ce963
// flow-typed version: <<STUB>>/next-transpile-modules_v^3.3.0/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-transpile-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-transpile-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-transpile-modules/src/next-transpile-modules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-transpile-modules/src/next-transpile-modules.js' {
  declare module.exports: $Exports<'next-transpile-modules/src/next-transpile-modules'>;
}
