// flow-typed signature: fd93c959089153c1e58a872bb7dfa22b
// flow-typed version: <<STUB>>/@babel/plugin-proposal-function-bind_v^7.8.3/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-function-bind'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-function-bind' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-function-bind/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-function-bind/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-function-bind/lib'>;
}
declare module '@babel/plugin-proposal-function-bind/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-function-bind/lib'>;
}
